#!/usr/bin/env python3
"""
verify_gate1.py - Hard Gate 1 for the EMS revision (plan 12A, step 1).

Question: do the artifacts regenerated by run_paper_pipeline.py reproduce the
numbers currently PRINTED in paper_draft_working.tex?

Nothing in the revision may be built on an artifact that does not reproduce its
printed number, so this runs before any other analysis.

It also tests the P1.4 hypothesis directly: the paper carries two different
Top-1 ranges for A_H on the same scenarios (89.7-93.1 at :244 vs 91.3-94.3 at
:1125). Table 8's caption says LLM rows are "per-type arithmetic means", but the
metrics file also carries an 'Overall' row per run. If those two aggregations
differ by about the observed gap, the discrepancy is explained.

Usage:
    python paper_pipeline/verify_gate1.py
"""

from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
METRICS = PROJECT_ROOT / "paper" / "per_run_metrics" / "per_run_metrics_all.csv"
OUT = PROJECT_ROOT / "Analysis" / "gate1_verification_2026-08-12.md"

ARCH_LABEL = {
    "Direct_LLM_Scoring": "A_D",
    "Example-Guided_LLM_Scoring": "A_E",
    "LLM-Parameterized_Reference_Scoring": "A_H",
}

# What the abstract prints, at paper_draft_working.tex:244.
PRINTED = {
    "A_H": {"tau": (0.880, 0.923), "top1": (0.897, 0.931)},
    "A_E": {"tau": (0.207, 0.328), "top1": (0.470, 0.545)},
    "A_D": {"tau": (0.010, 0.176), "top1": (0.300, 0.367)},
}
# The competing A_H Top-1 range printed at :1125.
PRINTED_ALT_AH_TOP1 = (0.913, 0.943)

TYPES = ["HVAC", "Appliance", "Shower"]
TOL = 0.0006  # printed to 3 dp / 1 dp percent


def aggregate(df, how):
    """Mean tau and top-1 per (model, architecture) under one aggregation."""
    if how == "overall_row":
        sub = df[df["decision_type"] == "Overall"]
        per_run = sub.groupby(["model", "architecture", "run"], as_index=False)[
            ["kendall_tau", "top1_accuracy"]].mean()
    else:  # per-type arithmetic mean, then across runs
        sub = df[df["decision_type"].isin(TYPES)]
        per_run = sub.groupby(["model", "architecture", "run"], as_index=False)[
            ["kendall_tau", "top1_accuracy"]].mean()
    return per_run.groupby(["model", "architecture"], as_index=False)[
        ["kendall_tau", "top1_accuracy"]].mean()


def ranges(agg):
    """Min-max across models, per architecture."""
    out = {}
    for arch, g in agg.groupby("architecture"):
        label = ARCH_LABEL.get(arch, arch)
        out[label] = {
            "tau": (g["kendall_tau"].min(), g["kendall_tau"].max()),
            "top1": (g["top1_accuracy"].min(), g["top1_accuracy"].max()),
        }
    return out


def verdict(computed, printed):
    lo_ok = abs(computed[0] - printed[0]) <= TOL
    hi_ok = abs(computed[1] - printed[1]) <= TOL
    if lo_ok and hi_ok:
        return "MATCH"
    drift = max(abs(computed[0] - printed[0]), abs(computed[1] - printed[1]))
    return f"MISMATCH (max drift {drift:.4f})"


def main():
    df = pd.read_csv(METRICS)
    lines = [
        "# Hard Gate 1 - artifact/manuscript reproduction check",
        "",
        "Generated by `paper_pipeline/verify_gate1.py` against",
        "`paper/per_run_metrics/per_run_metrics_all.csv` as regenerated by a clean",
        "full run of `run_paper_pipeline.py` (exit 0, all stages OK).",
        "",
        f"- Rows: {len(df)}",
        f"- Models: {', '.join(sorted(df['model'].unique()))}",
        f"- Architectures: {', '.join(sorted(df['architecture'].unique()))}",
        "",
    ]

    # Run counts per cell - relevant to the Gemini three-run disclosure.
    rc = (df[df["decision_type"] == "Overall"]
          .groupby(["model", "architecture"])["run"].nunique().reset_index())
    lines += ["## Run counts per cell", "",
              "| Model | Architecture | Runs |", "|---|---|---|"]
    for _, r in rc.iterrows():
        lines.append(f"| {r['model']} | {ARCH_LABEL.get(r['architecture'], r['architecture'])} "
                     f"| {r['run']} |")
    lines.append("")

    results = {}
    for how, title in [("overall_row", "Aggregation A - 'Overall' row per run"),
                       ("per_type", "Aggregation B - per-type arithmetic mean")]:
        agg = aggregate(df, how)
        rng = ranges(agg)
        results[how] = rng
        lines += [f"## {title}", "",
                  "| Arch | tau range (computed) | tau printed | verdict "
                  "| Top-1 range (computed) | Top-1 printed | verdict |",
                  "|---|---|---|---|---|---|---|"]
        for label in ["A_D", "A_E", "A_H"]:
            if label not in rng:
                continue
            c = rng[label]
            p = PRINTED[label]
            lines.append(
                f"| {label} "
                f"| {c['tau'][0]:.4f}-{c['tau'][1]:.4f} "
                f"| {p['tau'][0]:.3f}-{p['tau'][1]:.3f} "
                f"| {verdict(c['tau'], p['tau'])} "
                f"| {c['top1'][0]:.4f}-{c['top1'][1]:.4f} "
                f"| {p['top1'][0]:.3f}-{p['top1'][1]:.3f} "
                f"| {verdict(c['top1'], p['top1'])} |")
        lines.append("")

    # P1.4: does either aggregation explain the competing :1125 range?
    lines += ["## P1.4 - the two competing A_H Top-1 ranges", "",
              f"Abstract `:244` prints {PRINTED['A_H']['top1'][0]:.3f}-"
              f"{PRINTED['A_H']['top1'][1]:.3f}; `:1125` prints "
              f"{PRINTED_ALT_AH_TOP1[0]:.3f}-{PRINTED_ALT_AH_TOP1[1]:.3f}.", ""]
    for how, title in [("overall_row", "Aggregation A"), ("per_type", "Aggregation B")]:
        if "A_H" not in results[how]:
            continue
        c = results[how]["A_H"]["top1"]
        lines.append(f"- {title}: computed {c[0]:.4f}-{c[1]:.4f} "
                     f"| vs `:244` {verdict(c, PRINTED['A_H']['top1'])} "
                     f"| vs `:1125` {verdict(c, PRINTED_ALT_AH_TOP1)}")
    lines.append("")

    # Failure loads - feeds P1.2 / P1.3.
    fl = (df[df["decision_type"] == "Overall"]
          .groupby(["model", "architecture"])
          .agg(mean_failed=("n_failed", "mean"),
               max_failed=("n_failed", "max"),
               mean_scored=("n_scenarios", "mean")).reset_index())
    fl = fl[fl["max_failed"] > 0]
    lines += ["## Non-zero failure loads (feeds P1.2 / P1.3)", ""]
    if len(fl):
        lines += ["| Model | Arch | mean failed/run | max failed | mean scored |",
                  "|---|---|---|---|---|"]
        for _, r in fl.iterrows():
            lines.append(f"| {r['model']} | {ARCH_LABEL.get(r['architecture'], r['architecture'])} "
                         f"| {r['mean_failed']:.2f} | {int(r['max_failed'])} "
                         f"| {r['mean_scored']:.1f} |")
    else:
        lines.append("None.")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")

    print("GATE 1 VERIFICATION")
    print("=" * 60)
    for how, title in [("overall_row", "Aggregation A (Overall row)"),
                       ("per_type", "Aggregation B (per-type mean)")]:
        print(f"\n{title}")
        for label in ["A_D", "A_E", "A_H"]:
            if label not in results[how]:
                continue
            c = results[how][label]
            p = PRINTED[label]
            print(f"  {label}  tau {c['tau'][0]:.4f}-{c['tau'][1]:.4f} "
                  f"(printed {p['tau'][0]:.3f}-{p['tau'][1]:.3f}) {verdict(c['tau'], p['tau'])}")
            print(f"        top1 {c['top1'][0]:.4f}-{c['top1'][1]:.4f} "
                  f"(printed {p['top1'][0]:.3f}-{p['top1'][1]:.3f}) {verdict(c['top1'], p['top1'])}")
    print(f"\nWrote {OUT.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
